# The URL the site will be built for
base_url = "https://docs.msupply.foundation/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "adidoks"
default_language = "en"

[languages.en]
title = "mSupply documentation + user guides"
description = "Documentation and user guides for the mSupply foundation suite of software products. Here you'll find the user guide for notify, mSupply dashboard, health supply hub and mSupply mobile. There is also the user documentation for Open mSupply, Conforma, mSupply and mSupply cold chain."
build_search_index = true

[languages.en.translations]
flag = "en.svg"
TOCtitle = "On this page"
search_placeholder = "Search docs (whole words)..."

[languages.fr]
generate_feeds = true     # there will be a feed for French content
title = "mSupply ðŸ‡«ðŸ‡·"
build_search_index = true

[languages.fr.translations]
summary = "Mon blog"
title = "mSupply.fr"
flag = "fr.svg"
TOCtitle = "Sur cette page"
search_placeholder = "Rechercher des documents..."

[languages.es]
generate_feeds = true     # there will be a feed for Spanish content
title = "mSupply ðŸ‡ªðŸ‡¸"
build_search_index = true

[languages.es.translations]
summary = "Mi blog"
title = "mSupply.es"
flag = "es.svg"
TOCtitle = "En esta pagina"
search_placeholder = "Buscar documentos..."

[languages.pt]
generate_feeds = true     # there will be a feed for Portuguese content
title = "mSupply ðŸ‡µðŸ‡¹"
build_search_index = true

[languages.pt.translations]
title = "mSupply.pt"
flag = "pt.svg"
TOCtitle = "Nesta pÃ¡gina"
search_placeholder = "Pesquisar documentos..."


[search]

# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

# Whether to produce the search index as a javascript file or as a JSON file
# Accepted values:
# - "elasticlunr_javascript", "elasticlunr_json"
# - "fuse_javascript", "fuse_json"
index_format = "elasticlunr_javascript"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[extra]
# Put all your custom variables here

# Set theme-color meta tag for Chrome browser
theme_color = "#fff"

# Set HTML file language
language_code = "en-US"

# More about site's title
title_separator = "-" # set as |, -, _, etc
#itle_addition = "Open mSupply... Health Supply Chain Management for the World"

# Set date format in blog publish metadata
timeformat = "%B %e, %Y"      # e.g. June 14, 2021
timezone = "America/New_York"

# Github repo for the edit button on pages...
edit_page = false
docs_repo = "https://github.com/openmsupply/mSupply_docs"
repo_branch = "main"

# Menu items
[[extra.menu.main]]
name = ""
section = "docs"
url = "/docs/introduction/introduction"
weight = 10

[[extra.menu.social]]
name = "Twitter"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>'
url = "https://x.com/mSupply"
weight = 10
